version: '3.1'

services:
  mysql_db:
    image: mysql:8.3
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=kotlin_demo
      - MYSQL_USER=teddythinh
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"